// apps/web/utils/requestId.ts
/**
 * Retrieve the request ID that was generated by the middleware.
 * If the client supplied its own X-Request-ID header, that value is used;
 * otherwise the middleware generated one and added it to the response.
 * Handlers can call this helper for logging purposes.
 */
export function getRequestId(request: Request): string {
  return request.headers.get('x-request-id') ?? 'unknown';
}
